import type { WorkflowStudioDemoV11 } from './types'
import {
  toProcessGraph,
  type BaPrototypeProject,
  type ProcessModel,
  type ProjectSummary,
} from './prototype'

/**
 * Demo data for the BA Studio UI prototype: one fully worked project ("Business customer
 * onboarding & KYC" at a fictional bank) typed against the real contract plus the prototype
 * extensions, and a few portfolio rows for the projects home. Every screen reads from here until
 * the plumbing phase swaps it for the BA Studio gatekeeper, screen by screen.
 */

export const DEMO_PROJECT_ID = 'demo-sme-onboarding'
const PROCESS_ID = 'proc-sme-onboarding'

const stakeholders: WorkflowStudioDemoV11['requirements']['stakeholders'] = [
  { id: 'sh-sponsor', name: 'Priya Shah', role: 'Head of Business Banking (sponsor)' },
  { id: 'sh-ops', name: 'Tom Okafor', role: 'Onboarding Operations Lead' },
  { id: 'sh-kyc', name: 'Elena Varga', role: 'KYC & Financial Crime Officer' },
  { id: 'sh-rm', name: 'Marcus Lee', role: 'Relationship Manager' },
  { id: 'sh-it', name: 'Aisha Rahman', role: 'Integration Architect' },
  { id: 'sh-customer', name: 'SME customer (persona)', role: 'Business owner applying for an account' },
]

const asIs: ProcessModel = {
  lanes: [
    { id: 'lane-customer', label: 'Customer', stakeholderId: 'sh-customer' },
    { id: 'lane-rm', label: 'Relationship Manager', stakeholderId: 'sh-rm' },
    { id: 'lane-ops', label: 'Onboarding Ops', stakeholderId: 'sh-ops' },
    { id: 'lane-kyc', label: 'KYC / Compliance', stakeholderId: 'sh-kyc' },
  ],
  nodes: [
    { id: 'a-start', type: 'startEvent', label: 'Customer emails documents', laneId: 'lane-customer', column: 0 },
    { id: 'a-rekey', type: 'manualTask', label: 'Re-key application into CRM', laneId: 'lane-rm', column: 1, slaHours: 24 },
    { id: 'a-check', type: 'userTask', label: 'Check pack completeness', laneId: 'lane-ops', column: 2, slaHours: 48 },
    { id: 'a-complete', type: 'exclusiveGateway', label: 'Pack complete?', laneId: 'lane-ops', column: 3 },
    { id: 'a-chase', type: 'manualTask', label: 'Chase missing documents by email', laneId: 'lane-customer', column: 3, slaHours: 72 },
    { id: 'a-screen', type: 'userTask', label: 'Manual sanctions & PEP screening', laneId: 'lane-kyc', column: 4, slaHours: 72 },
    { id: 'a-edd', type: 'userTask', label: 'Review every file for EDD', laneId: 'lane-kyc', column: 5, slaHours: 48 },
    { id: 'a-open', type: 'manualTask', label: 'Open account in core banking', laneId: 'lane-ops', column: 6, slaHours: 24 },
    { id: 'a-end', type: 'endEvent', label: 'Account opened', laneId: 'lane-customer', column: 7 },
  ],
  edges: [
    { id: 'ae1', source: 'a-start', target: 'a-rekey' },
    { id: 'ae2', source: 'a-rekey', target: 'a-check' },
    { id: 'ae3', source: 'a-check', target: 'a-complete' },
    { id: 'ae4', source: 'a-complete', target: 'a-chase', condition: 'No (62%)', isException: true },
    { id: 'ae5', source: 'a-chase', target: 'a-check', isException: true },
    { id: 'ae6', source: 'a-complete', target: 'a-screen', condition: 'Yes' },
    { id: 'ae7', source: 'a-screen', target: 'a-edd' },
    { id: 'ae8', source: 'a-edd', target: 'a-open' },
    { id: 'ae9', source: 'a-open', target: 'a-end' },
  ],
}

const toBe: ProcessModel = {
  lanes: [
    { id: 'lane-customer', label: 'Customer', stakeholderId: 'sh-customer' },
    { id: 'lane-platform', label: 'Onboarding platform' },
    { id: 'lane-kyc', label: 'KYC / Compliance', stakeholderId: 'sh-kyc' },
    { id: 'lane-rm', label: 'Relationship Manager', stakeholderId: 'sh-rm' },
  ],
  nodes: [
    { id: 't-start', type: 'startEvent', label: 'Customer applies online', laneId: 'lane-customer', column: 0, requirementIds: ['R-01'] },
    { id: 't-docs', type: 'serviceTask', label: 'Verify documents & Companies House', laneId: 'lane-platform', column: 1, slaHours: 0.1, requirementIds: ['R-02'] },
    { id: 't-docs-ok', type: 'exclusiveGateway', label: 'Documents verified?', laneId: 'lane-platform', column: 2 },
    { id: 't-reminder', type: 'timerEvent', label: 'Nudge customer after 48h', laneId: 'lane-customer', column: 2, isException: true, requirementIds: ['R-07'] },
    { id: 't-screen', type: 'serviceTask', label: 'Automated sanctions & PEP screening', laneId: 'lane-platform', column: 3, slaHours: 0.1, requirementIds: ['R-03'] },
    { id: 't-risk', type: 'exclusiveGateway', label: 'Risk tier (DMN)', laneId: 'lane-platform', column: 4, decisionTableId: 'DT-01', requirementIds: ['R-04'] },
    { id: 't-review', type: 'userTask', label: 'Compliance review (medium risk)', laneId: 'lane-kyc', column: 5, slaHours: 24, approval: true, requirementIds: ['R-05'] },
    { id: 't-edd', type: 'userTask', label: 'Enhanced due diligence (high risk)', laneId: 'lane-kyc', column: 6, slaHours: 72, approval: true, requirementIds: ['R-05'] },
    { id: 't-open', type: 'serviceTask', label: 'Open account via core banking API', laneId: 'lane-platform', column: 7, slaHours: 0.5, requirementIds: ['R-06'] },
    { id: 't-welcome', type: 'userTask', label: 'Welcome call & needs review', laneId: 'lane-rm', column: 8, slaHours: 48, requirementIds: ['R-08'] },
    { id: 't-declined', type: 'endEvent', label: 'Application declined', laneId: 'lane-kyc', column: 8, isException: true },
    { id: 't-end', type: 'endEvent', label: 'Customer live', laneId: 'lane-customer', column: 9 },
  ],
  edges: [
    { id: 'te1', source: 't-start', target: 't-docs' },
    { id: 'te2', source: 't-docs', target: 't-docs-ok' },
    { id: 'te3', source: 't-docs-ok', target: 't-screen', condition: 'Verified' },
    { id: 'te4', source: 't-docs-ok', target: 't-reminder', condition: 'Missing / unreadable', isException: true },
    { id: 'te5', source: 't-reminder', target: 't-docs', isException: true },
    { id: 'te6', source: 't-screen', target: 't-risk' },
    { id: 'te7', source: 't-risk', target: 't-open', condition: 'Low' },
    { id: 'te8', source: 't-risk', target: 't-review', condition: 'Medium' },
    { id: 'te9', source: 't-risk', target: 't-edd', condition: 'High' },
    { id: 'te10', source: 't-review', target: 't-open', condition: 'Approved' },
    { id: 'te11', source: 't-review', target: 't-edd', condition: 'Escalate' },
    { id: 'te12', source: 't-edd', target: 't-open', condition: 'Approved' },
    { id: 'te13', source: 't-edd', target: 't-declined', condition: 'Rejected', isException: true },
    { id: 'te14', source: 't-open', target: 't-welcome' },
    { id: 'te15', source: 't-welcome', target: 't-end' },
  ],
}

const bundle: WorkflowStudioDemoV11 = {
  contractVersion: 'workflow-studio-demo/v1.1',
  processName: 'Business customer onboarding & KYC',
  requirements: {
    schemaVersion: 'requirements/v1.1',
    processId: PROCESS_ID,
    generatedAt: '2026-09-24T10:12:00.000Z',
    stakeholders,
    requirements: [
      {
        id: 'R-01',
        title: 'Single digital application',
        category: 'functional',
        statement: 'The customer shall be able to apply, upload documents and track status in one online journey without re-keying by staff.',
        acceptanceCriteria: [
          'Given a new SME applicant, when they complete the form, then no staff re-keying is needed to create the CRM record.',
          'Status is visible to the customer at every step.',
        ],
        priority: 'must',
        ownerStakeholderId: 'sh-ops',
        sourceStakeholderIds: ['sh-customer', 'sh-rm'],
        fitCriterion: '0 manual CRM entries per application in pilot.',
        benefitHypothesis: 'Removing re-keying cuts ~1 day of cycle time and most transcription defects.',
      },
      {
        id: 'R-02',
        title: 'Automated document & registry verification',
        category: 'integration',
        statement: 'The platform shall verify identity documents and company details against Companies House automatically on upload.',
        acceptanceCriteria: [
          'Unreadable or mismatched documents are flagged to the customer within 1 minute.',
          'Verified company officers are pre-filled into the ownership structure.',
        ],
        priority: 'must',
        ownerStakeholderId: 'sh-it',
        sourceStakeholderIds: ['sh-ops'],
        fitCriterion: '≥ 80% of packs verified with no human touch.',
        benefitHypothesis: 'Most rework today is incomplete packs caught days later.',
      },
      {
        id: 'R-03',
        title: 'Automated sanctions & PEP screening',
        category: 'compliance',
        statement: 'All applicants and beneficial owners shall be screened against sanctions and PEP lists automatically, with an auditable result.',
        acceptanceCriteria: ['Every screening result is stored with list version and timestamp.', 'Potential matches route to Compliance.'],
        priority: 'must',
        ownerStakeholderId: 'sh-kyc',
        sourceStakeholderIds: ['sh-kyc'],
        fitCriterion: '100% of files carry an auditable screening record.',
        benefitHypothesis: 'Removes the largest single queue and most audit defects.',
      },
      {
        id: 'R-04',
        title: 'Rules-based risk tiering',
        category: 'compliance',
        statement: 'Each application shall be assigned a low, medium or high risk tier by an explicit, versioned decision table.',
        acceptanceCriteria: ['Tiering rules are readable by Compliance and versioned.', 'Every tier decision is explainable from its inputs.'],
        priority: 'must',
        ownerStakeholderId: 'sh-kyc',
        sourceStakeholderIds: ['sh-kyc', 'sh-sponsor'],
        fitCriterion: 'Compliance can reproduce any tier decision from the audit log.',
        benefitHypothesis: 'Lets low-risk files skip manual review safely.',
      },
      {
        id: 'R-05',
        title: 'Risk-proportionate human review',
        category: 'compliance',
        statement: 'Medium-risk files shall get a compliance review within 24h and high-risk files enhanced due diligence within 72h.',
        acceptanceCriteria: ['Review SLAs are tracked and breached items escalate.', 'Reviewers see the tier rationale and evidence in one view.'],
        priority: 'must',
        ownerStakeholderId: 'sh-kyc',
        sourceStakeholderIds: ['sh-kyc', 'sh-ops'],
        fitCriterion: '95% of reviews within SLA.',
        benefitHypothesis: 'Focuses expert time where risk is, not on every file.',
      },
      {
        id: 'R-06',
        title: 'Straight-through account opening',
        category: 'integration',
        statement: 'Approved applications shall open the account in core banking via API without manual entry.',
        acceptanceCriteria: ['Account number returned to customer within 30 minutes of approval.'],
        priority: 'should',
        ownerStakeholderId: 'sh-it',
        sourceStakeholderIds: ['sh-ops'],
        fitCriterion: '0 manual core banking entries for approved files.',
        benefitHypothesis: 'Removes the last manual hand-off and its errors.',
        dependencies: ['R-04'],
      },
      {
        id: 'R-07',
        title: 'Automated reminders for incomplete applications',
        category: 'functional',
        statement: 'Customers with missing or unreadable documents shall be reminded automatically after 48 hours.',
        acceptanceCriteria: ['Reminder sent at 48h and 5 days; application closes at 14 days with notice.'],
        priority: 'should',
        ownerStakeholderId: 'sh-ops',
        sourceStakeholderIds: ['sh-customer'],
        fitCriterion: 'Abandonment of incomplete applications halves in pilot.',
        benefitHypothesis: 'Most abandonment is silent drop-off after a document request.',
      },
      {
        id: 'R-08',
        title: 'RM welcome call after opening',
        category: 'functional',
        statement: 'The relationship manager shall contact every new customer within 48 hours of account opening.',
        acceptanceCriteria: ['Welcome task created automatically with application context.'],
        priority: 'could',
        ownerStakeholderId: 'sh-rm',
        sourceStakeholderIds: ['sh-rm'],
        fitCriterion: '90% of new customers contacted within 48h.',
        benefitHypothesis: 'Keeps the relationship while moving intake to self-serve.',
      },
      {
        id: 'R-09',
        title: 'Real-time onboarding dashboard',
        category: 'reporting',
        statement: 'Operations shall see live volumes, queue ages and SLA breaches by stage.',
        acceptanceCriteria: ['Dashboard refreshes at least every 5 minutes.'],
        priority: 'wont',
        ownerStakeholderId: 'sh-ops',
        sourceStakeholderIds: ['sh-ops'],
        fitCriterion: 'Deferred to phase 2.',
        benefitHypothesis: 'Useful, but no outcome depends on it for launch.',
      },
    ],
    raci: [
      { activityId: 't-docs', responsible: ['sh-it'], accountable: 'sh-ops', consulted: ['sh-kyc'], informed: ['sh-rm'] },
      { activityId: 't-screen', responsible: ['sh-it'], accountable: 'sh-kyc', consulted: [], informed: ['sh-ops'] },
      { activityId: 't-risk', responsible: ['sh-kyc'], accountable: 'sh-kyc', consulted: ['sh-sponsor'], informed: ['sh-ops'] },
      { activityId: 't-review', responsible: ['sh-kyc'], accountable: 'sh-kyc', consulted: ['sh-rm'], informed: ['sh-ops'] },
      { activityId: 't-open', responsible: ['sh-it'], accountable: 'sh-ops', consulted: [], informed: ['sh-rm', 'sh-customer'] },
      { activityId: 't-welcome', responsible: ['sh-rm'], accountable: 'sh-sponsor', consulted: [], informed: ['sh-ops'] },
    ],
    decisionLog: [
      {
        id: 'D-01',
        summary: 'Low-risk files open without manual compliance review',
        rationale: 'DMN tiering is auditable and Compliance owns the rules; manual review of low risk added 3 days with no findings in 12 months of audit samples.',
        requirementIds: ['R-04', 'R-05'],
        ownerStakeholderId: 'sh-kyc',
        status: 'approved',
      },
      {
        id: 'D-02',
        summary: 'Adopt hybrid option: vendor KYC API + in-house orchestration',
        rationale: 'Best combined impact on speed and audit quality; keeps the process model and rules in our control.',
        requirementIds: ['R-02', 'R-03', 'R-06'],
        ownerStakeholderId: 'sh-sponsor',
        status: 'approved',
      },
      {
        id: 'D-03',
        summary: 'RM welcome call replaces RM-led intake',
        rationale: 'Keeps relationship value while removing RM re-keying from the critical path.',
        requirementIds: ['R-01', 'R-08'],
        ownerStakeholderId: 'sh-sponsor',
        status: 'proposed',
      },
    ],
    stakeholderSuggestions: [
      {
        id: 'SS-01',
        role: 'Data Protection Officer',
        reason: 'New automated screening processes personal data of beneficial owners; a DPIA is likely required.',
        source: 'gapAnalysis',
        suggestedAt: '2026-09-22T09:00:00.000Z',
      },
      {
        id: 'SS-02',
        name: 'Customer Service Team Lead',
        role: 'Front-line support',
        reason: 'Customers stuck on document upload will call support; they are not represented yet.',
        source: 'interview',
        suggestedAt: '2026-09-23T14:30:00.000Z',
      },
    ],
  },
  conflictRegister: {
    schemaVersion: 'conflicts/v1.1',
    processId: PROCESS_ID,
    conflicts: [
      {
        id: 'C-01',
        summary: 'Compliance wants every medium-risk file manually reviewed; Ops wants medium risk auto-approved when documents verify cleanly.',
        requirementIds: ['R-04', 'R-05'],
        stakeholderIds: ['sh-kyc', 'sh-ops'],
        impact: 'compliance',
        resolutionOwnerStakeholderId: 'sh-sponsor',
        decision: { status: 'resolved' },
      },
      {
        id: 'C-02',
        summary: 'RMs want to keep first contact with every applicant; self-serve intake removes it.',
        requirementIds: ['R-01', 'R-08'],
        stakeholderIds: ['sh-rm', 'sh-ops'],
        impact: 'scope',
        resolutionOwnerStakeholderId: 'sh-sponsor',
        decision: { status: 'inReview' },
      },
      {
        id: 'C-03',
        summary: 'Real-time dashboard requested for launch would push go-live by ~6 weeks.',
        requirementIds: ['R-09'],
        stakeholderIds: ['sh-ops', 'sh-it'],
        impact: 'timeline',
        resolutionOwnerStakeholderId: 'sh-sponsor',
        decision: { status: 'deferred' },
      },
    ],
  },
  processGraph: toProcessGraph(PROCESS_ID, toBe),
  tradeoffRegister: {
    schemaVersion: 'tradeoffs/v1.1',
    processId: PROCESS_ID,
    options: [
      {
        id: 'OPT-A',
        title: 'Extend existing CRM workflow',
        summary: 'Build the journey and screening orchestration inside the current CRM.',
        scores: { userValue: 2, deliveryEffort: 3, operationalRisk: 3, complianceFit: 3 },
        impacts: { scope: 'medium', cost: 'low', timeline: 'medium', risk: 'medium' },
      },
      {
        id: 'OPT-B',
        title: 'Buy end-to-end onboarding SaaS',
        summary: 'Replace the journey with a vendor product including KYC and workflow.',
        scores: { userValue: 4, deliveryEffort: 4, operationalRisk: 2, complianceFit: 3 },
        impacts: { scope: 'high', cost: 'high', timeline: 'low', risk: 'medium' },
      },
      {
        id: 'OPT-C',
        title: 'Hybrid: vendor KYC API + in-house orchestration',
        summary: 'Use a KYC vendor for verification and screening; own the process model, rules and journey.',
        scores: { userValue: 4, deliveryEffort: 3, operationalRisk: 4, complianceFit: 5 },
        impacts: { scope: 'medium', cost: 'medium', timeline: 'medium', risk: 'low' },
      },
    ],
    preferredOptionId: 'OPT-C',
  },
  signoffPacket: {
    schemaVersion: 'signoff/v1.1',
    processId: PROCESS_ID,
    baselineVersion: '1.0',
    approvedAt: '',
    approvers: [
      { stakeholderId: 'sh-sponsor', role: 'Sponsor', decision: 'approved', note: 'Approved subject to C-02 closing before build.' },
      { stakeholderId: 'sh-kyc', role: 'Compliance', decision: 'approvedWithConditions', note: 'DMN rule changes need Compliance approval each release.' },
      { stakeholderId: 'sh-ops', role: 'Operations', decision: 'approved' },
      { stakeholderId: 'sh-it', role: 'Architecture', decision: 'approvedWithConditions', note: 'Vendor due diligence to complete before contract.' },
    ],
  },
  viewer: {
    selectedRequirementId: 'R-04',
    highlightedConflictId: 'C-02',
    highlightedTradeoffOptionId: 'OPT-C',
  },
}

export const DEMO_PROJECT: BaPrototypeProject = {
  summary: {
    id: DEMO_PROJECT_ID,
    processName: bundle.processName,
    sponsor: 'Priya Shah',
    currentStage: 'signoff',
    updatedAt: '2026-09-26T16:40:00.000Z',
    outcomeHealth: 'onTrack',
    openConflicts: 1,
    pendingSignoffs: 2,
    openable: true,
  },
  stageStatus: {
    outcomes: 'done',
    stakeholders: 'attention',
    'as-is': 'done',
    requirements: 'done',
    'to-be': 'done',
    tradeoffs: 'attention',
    validate: 'done',
    signoff: 'active',
    handoff: 'notStarted',
    monitor: 'notStarted',
  },
  bundle,
  framing: {
    problemStatement:
      'Opening a business account takes a median of 12 working days. 62% of applications need rework for missing documents, a third of applicants abandon, and KYC files fail internal audit at 14 defects per 100.',
    benefitHypothesis:
      'If we move intake to a verified digital journey and apply risk-proportionate review, SMEs will be live in days not weeks, Compliance will have cleaner files, and cost to onboard will fall by more than half.',
    scopeIn: ['New SME current account applications (UK, sole traders excluded)', 'KYC/KYB, sanctions & PEP screening', 'Account opening in core banking', 'RM hand-over after opening'],
    scopeOut: ['Lending and credit decisions', 'Existing customer periodic reviews', 'Sole traders and charities (phase 2)'],
    assumptions: ['KYC vendor API meets FCA record-keeping needs', 'Core banking account-opening API is available in Q1'],
    constraints: ['Money Laundering Regulations 2017', 'Go-live before end of Q2', 'No new headcount'],
    outcomes: [
      {
        id: 'O-1',
        title: 'SMEs are live in days, not weeks',
        statement: 'Cut median time from application to usable account from 12 to 3 working days by end of Q2.',
        ownerStakeholderId: 'sh-sponsor',
        smart: { specific: true, measurable: true, achievable: true, relevant: true, timeBound: true },
      },
      {
        id: 'O-2',
        title: 'Audit-ready KYC by default',
        statement: 'Every file carries a complete, auditable screening and risk record; audit defects fall to ≤ 2 per 100.',
        ownerStakeholderId: 'sh-kyc',
        smart: { specific: true, measurable: true, achievable: true, relevant: true, timeBound: true },
      },
      {
        id: 'O-3',
        title: 'Fewer applicants give up',
        statement: 'Halve abandonment and lower the cost to onboard each customer.',
        ownerStakeholderId: 'sh-ops',
        smart: { specific: true, measurable: true, achievable: true, relevant: true, timeBound: false },
      },
    ],
    measures: [
      { id: 'M-1', outcomeId: 'O-1', name: 'Median cycle time', unit: 'days', baseline: 12, target: 3, direction: 'decrease', source: 'CRM timestamps', cadence: 'Weekly' },
      { id: 'M-2', outcomeId: 'O-1', name: 'First-time-right applications', unit: '%', baseline: 38, target: 75, direction: 'increase', source: 'Ops rework log', cadence: 'Weekly' },
      { id: 'M-3', outcomeId: 'O-2', name: 'KYC audit defects', unit: 'per 100 files', baseline: 14, target: 2, direction: 'decrease', source: 'Internal audit sample', cadence: 'Monthly' },
      { id: 'M-4', outcomeId: 'O-3', name: 'Application abandonment', unit: '%', baseline: 31, target: 15, direction: 'decrease', source: 'Web analytics', cadence: 'Weekly' },
      { id: 'M-5', outcomeId: 'O-3', name: 'Cost to onboard', unit: '£ / customer', baseline: 410, target: 180, direction: 'decrease', source: 'Finance activity costing', cadence: 'Quarterly' },
    ],
  },
  requirementOutcomes: {
    'R-01': ['O-1', 'O-3'],
    'R-02': ['O-1', 'O-2'],
    'R-03': ['O-2'],
    'R-04': ['O-1', 'O-2'],
    'R-05': ['O-2'],
    'R-06': ['O-1', 'O-3'],
    'R-07': ['O-3'],
    'R-08': [],
    'R-09': [],
  },
  stakeholderProfiles: [
    { stakeholderId: 'sh-sponsor', influence: 5, interest: 5, stance: 'champion', engagement: 'Manage closely · fortnightly steering' },
    { stakeholderId: 'sh-kyc', influence: 5, interest: 4, stance: 'neutral', engagement: 'Manage closely · co-own decision rules' },
    { stakeholderId: 'sh-ops', influence: 3, interest: 5, stance: 'champion', engagement: 'Keep informed · weekly working session' },
    { stakeholderId: 'sh-rm', influence: 3, interest: 3, stance: 'sceptic', engagement: 'Keep satisfied · address C-02 directly' },
    { stakeholderId: 'sh-it', influence: 4, interest: 2, stance: 'supporter', engagement: 'Keep satisfied · architecture reviews' },
    { stakeholderId: 'sh-customer', influence: 2, interest: 5, stance: 'neutral', engagement: 'Keep informed · usability testing' },
  ],
  sipoc: {
    suppliers: ['SME applicant', 'Companies House', 'Sanctions / PEP list provider', 'Credit reference agency'],
    inputs: ['Application details', 'ID & address documents', 'Company registry data', 'Screening results'],
    process: ['Apply', 'Verify documents', 'Screen', 'Assess risk', 'Review (if needed)', 'Open account', 'Welcome'],
    outputs: ['Open business account', 'Auditable KYC file', 'Risk tier', 'Welcome pack'],
    customers: ['SME customer', 'Relationship Manager', 'Compliance & Internal Audit', 'Regulator (FCA)'],
  },
  asIs,
  painPoints: [
    { id: 'P-1', nodeId: 'a-rekey', title: 'Application re-keyed from email into CRM', wasteType: 'overprocessing', annualCost: 96000, evidence: '1.4 FTE across RMs; 1 in 9 records has a transcription error.', measureId: 'M-2' },
    { id: 'P-2', nodeId: 'a-chase', title: 'Missing-document chase loop', wasteType: 'rework', annualCost: 142000, evidence: '62% of packs incomplete; average 2.3 chase cycles adding 4.1 days.', measureId: 'M-1' },
    { id: 'P-3', nodeId: 'a-screen', title: 'Manual screening queue', wasteType: 'waiting', annualCost: 118000, evidence: 'Files wait 3.2 days on average before a screener picks them up.', measureId: 'M-1' },
    { id: 'P-4', nodeId: 'a-edd', title: 'Every file reviewed at EDD depth', wasteType: 'overprocessing', annualCost: 88000, evidence: '81% of files are low risk yet get the same review; no findings in 12-month audit sample.', measureId: 'M-5' },
    { id: 'P-5', nodeId: 'a-open', title: 'Manual core banking entry', wasteType: 'defects', annualCost: 34000, evidence: '4% of accounts need correction after opening.', measureId: 'M-3' },
  ],
  toBe,
  decisionTables: [
    {
      id: 'DT-01',
      name: 'Onboarding risk tier',
      nodeId: 't-risk',
      hitPolicy: 'FIRST',
      inputs: ['Sanctions / PEP match', 'Jurisdiction risk', 'Ownership layers', 'Industry risk'],
      output: 'Risk tier',
      rules: [
        { when: ['Confirmed', '-', '-', '-'], result: 'High', annotation: 'Always EDD; may decline' },
        { when: ['Potential', '-', '-', '-'], result: 'Medium', annotation: 'Compliance to discount or escalate' },
        { when: ['None', 'High', '-', '-'], result: 'High', annotation: 'FATF high-risk list' },
        { when: ['None', '-', '> 2', '-'], result: 'Medium', annotation: 'Complex ownership' },
        { when: ['None', '-', '-', 'High'], result: 'Medium', annotation: 'e.g. MSB, crypto, gambling' },
        { when: ['None', 'Low / Medium', '≤ 2', 'Low / Medium'], result: 'Low', annotation: 'Straight-through' },
      ],
    },
  ],
  tradeoffImpacts: [
    { optionId: 'OPT-A', outcomeId: 'O-1', impact: 1, rationale: 'Some automation, but CRM workflow limits straight-through processing.' },
    { optionId: 'OPT-A', outcomeId: 'O-2', impact: 0, rationale: 'Screening stays largely manual.' },
    { optionId: 'OPT-A', outcomeId: 'O-3', impact: 1, rationale: 'Lowest cost, modest UX gains.' },
    { optionId: 'OPT-B', outcomeId: 'O-1', impact: 2, rationale: 'Fast out of the box.' },
    { optionId: 'OPT-B', outcomeId: 'O-2', impact: 1, rationale: 'Vendor rules are a black box to Compliance.' },
    { optionId: 'OPT-B', outcomeId: 'O-3', impact: 0, rationale: 'Licence cost offsets savings; generic journey.' },
    { optionId: 'OPT-C', outcomeId: 'O-1', impact: 2, rationale: 'Straight-through for ~80% of files.' },
    { optionId: 'OPT-C', outcomeId: 'O-2', impact: 2, rationale: 'Rules owned and versioned by Compliance; full audit trail.' },
    { optionId: 'OPT-C', outcomeId: 'O-3', impact: 1, rationale: 'Tailored journey; moderate build cost.' },
  ],
  projections: [
    { measureId: 'M-1', projected: 2.6, confidence: 'medium', basis: '80% low-risk straight-through; medium/high paths from SLA.' },
    { measureId: 'M-2', projected: 78, confidence: 'medium', basis: 'Upload-time verification catches most gaps.' },
    { measureId: 'M-3', projected: 2, confidence: 'high', basis: 'Every file carries an automated screening record.' },
    { measureId: 'M-4', projected: 17, confidence: 'low', basis: 'Benchmarks from comparable digital journeys; reminders assumed.' },
    { measureId: 'M-5', projected: 165, confidence: 'medium', basis: 'Activity costing with vendor per-check fees.' },
  ],
  findings: [
    { id: 'F-1', severity: 'gap', title: 'No path for customers who cannot upload documents', detail: 'Assisted-digital route is missing for customers without a smartphone or scanner.', nodeId: 't-docs', resolved: false },
    { id: 'F-2', severity: 'risk', title: 'M-4 projection misses its target', detail: 'Projected abandonment 17% vs target 15%. Consider saving progress and a clearer document checklist.', resolved: false },
    { id: 'F-3', severity: 'gap', title: 'R-08 has no outcome link', detail: 'Either link the welcome call to an outcome or move it to "won\'t" for this release.', requirementId: 'R-08', resolved: false },
    { id: 'F-4', severity: 'info', title: 'Decision table covers all input combinations', detail: 'DT-01 is complete under hit policy FIRST (final rule is the default).', nodeId: 't-risk', resolved: true },
    { id: 'F-5', severity: 'risk', title: 'EDD SLA depends on one team', detail: 'High-risk volume spikes could breach the 72h SLA; add an overflow rule.', nodeId: 't-edd', resolved: true },
  ],
  versions: [
    {
      version: '0.1',
      createdAt: '2026-09-10T11:00:00.000Z',
      author: 'BA agent · reviewed by Tom Okafor',
      summary: 'First draft from discovery interviews.',
      status: 'superseded',
      changes: [
        { kind: 'added', artifact: 'outcome', ref: 'O-1', summary: 'Cycle-time outcome framed' },
        { kind: 'added', artifact: 'requirement', ref: 'R-01…R-06', summary: 'Initial requirements elicited' },
      ],
    },
    {
      version: '0.2',
      createdAt: '2026-09-18T15:20:00.000Z',
      author: 'BA agent · reviewed by Elena Varga',
      summary: 'Compliance workshop: risk tiering and review paths.',
      status: 'superseded',
      changes: [
        { kind: 'added', artifact: 'decision', ref: 'DT-01', summary: 'DMN risk tier table' },
        { kind: 'changed', artifact: 'processStep', ref: 't-review', summary: 'Manual review limited to medium risk' },
        { kind: 'added', artifact: 'outcome', ref: 'O-2', summary: 'Audit-ready KYC outcome' },
        { kind: 'added', artifact: 'conflict', ref: 'C-01', summary: 'Medium-risk review conflict raised' },
      ],
    },
    {
      version: '1.0',
      createdAt: '2026-09-26T16:40:00.000Z',
      author: 'BA agent · submitted by Priya Shah',
      summary: 'Baseline candidate after trade-off decision and validation.',
      status: 'inReview',
      changes: [
        { kind: 'added', artifact: 'processStep', ref: 't-reminder', summary: 'Automated 48h reminder (exception path)' },
        { kind: 'added', artifact: 'requirement', ref: 'R-07', summary: 'Reminders requirement' },
        { kind: 'changed', artifact: 'requirement', ref: 'R-09', summary: 'Dashboard moved to won\'t (deferred)' },
        { kind: 'changed', artifact: 'conflict', ref: 'C-01', summary: 'Resolved via D-01' },
        { kind: 'removed', artifact: 'processStep', ref: 'a-rekey', summary: 'Re-keying removed from future state' },
      ],
    },
  ],
  buildTargets: [
    {
      id: 'B-1',
      kind: 'gadget',
      title: 'Compliance review workbench',
      description: 'A gadget for medium/high-risk reviews: evidence, tier rationale, approve / escalate / reject, SLA timer.',
      fit: 'recommended',
      coversNodeIds: ['t-review', 't-edd'],
    },
    {
      id: 'B-2',
      kind: 'scheduled',
      title: 'Incomplete application reminders',
      description: 'Scheduled task that nudges customers at 48h and 5 days and closes at 14 days.',
      fit: 'recommended',
      coversNodeIds: ['t-reminder'],
    },
    {
      id: 'B-3',
      kind: 'automation',
      title: 'Onboarding orchestration flow',
      description: 'Automated flow calling the KYC vendor, evaluating DT-01 and opening the account via API.',
      fit: 'possible',
      coversNodeIds: ['t-docs', 't-screen', 't-risk', 't-open'],
    },
  ],
  monitoring: [
    { measureId: 'M-1', points: [{ period: 'Pilot wk 1', actual: 9 }, { period: 'wk 2', actual: 7.5 }, { period: 'wk 3', actual: 5.8 }, { period: 'wk 4', actual: 4.4 }, { period: 'wk 5', actual: 3.6 }, { period: 'wk 6', actual: 3.1 }] },
    { measureId: 'M-2', points: [{ period: 'Pilot wk 1', actual: 49 }, { period: 'wk 2', actual: 58 }, { period: 'wk 3', actual: 66 }, { period: 'wk 4', actual: 71 }, { period: 'wk 5', actual: 74 }, { period: 'wk 6', actual: 77 }] },
    { measureId: 'M-3', points: [{ period: 'Month 1', actual: 6 }, { period: 'Month 2', actual: 3 }] },
    { measureId: 'M-4', points: [{ period: 'Pilot wk 1', actual: 28 }, { period: 'wk 2', actual: 25 }, { period: 'wk 3', actual: 22 }, { period: 'wk 4', actual: 20 }, { period: 'wk 5', actual: 19 }, { period: 'wk 6', actual: 18 }] },
    { measureId: 'M-5', points: [{ period: 'Q1 (pilot)', actual: 240 }] },
  ],
}

/** Portfolio rows for the projects home. Only the first has a full worked dataset. */
export const DEMO_PORTFOLIO: ProjectSummary[] = [
  DEMO_PROJECT.summary,
  {
    id: 'demo-invoice-approval',
    processName: 'Supplier invoice approval',
    sponsor: 'Finance Director',
    currentStage: 'to-be',
    updatedAt: '2026-09-25T09:15:00.000Z',
    outcomeHealth: 'atRisk',
    openConflicts: 3,
    pendingSignoffs: 0,
    openable: false,
  },
  {
    id: 'demo-offboarding',
    processName: 'Employee offboarding & access removal',
    sponsor: 'CISO',
    currentStage: 'monitor',
    updatedAt: '2026-09-12T13:05:00.000Z',
    outcomeHealth: 'onTrack',
    openConflicts: 0,
    pendingSignoffs: 0,
    openable: false,
  },
]

export function getDemoProject(projectId: string): BaPrototypeProject | null {
  return projectId === DEMO_PROJECT_ID ? DEMO_PROJECT : null
}
